INSERT INTO IMA15_stangl_project_2.UserRoleModel (userRoleId,role) VALUES (1,'ROLE_USER');
INSERT INTO IMA15_stangl_project_2.UserRoleModel (userRoleId,role) VALUES (2,'ROLE_ADMIN');
INSERT INTO IMA15_stangl_project_2.RecipeCategoryModel (idCategory,name,version) VALUES (1,'Drinks',0);
INSERT INTO IMA15_stangl_project_2.RecipeCategoryModel (idCategory,name,version) VALUES (2,'Sweets',0);
INSERT INTO IMA15_stangl_project_2.RecipeCategoryModel (idCategory,name,version) VALUES (3,'Cocktails',0);
INSERT INTO IMA15_stangl_project_2.RecipeCategoryModel (idCategory,name,version) VALUES (4,'Meat Dishes',0);
INSERT INTO IMA15_stangl_project_2.IngredientModel (idIngredient,name) VALUES (1,'Zucker');
INSERT INTO IMA15_stangl_project_2.IngredientModel (idIngredient,name) VALUES (2,'Mehl');
INSERT INTO IMA15_stangl_project_2.IngredientModel (idIngredient,name) VALUES (3,'Zitrone');
INSERT INTO IMA15_stangl_project_2.IngredientModel (idIngredient,name) VALUES (4,'Salz');
INSERT INTO IMA15_stangl_project_2.IngredientModel (idIngredient,name) VALUES (5,'Pfeffer');
INSERT INTO IMA15_stangl_project_2.IngredientModel (idIngredient,name) VALUES (6,'Milch');